"""Check every hand-written number in the manuscript against its source artefact.

The tables are generated by scripts/make_paper_tex.py and cannot drift. The prose
is written by hand and can, so each numeric claim in the body text is listed here
with the artefact it comes from and re-checked on demand. A claim that no longer
matches its source is a hard failure.

Source: every CSV under paper/tables/, written by the runner and by
scripts/make_paper_tex.py.

    python scripts/verify_paper_numbers.py
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parent.parent
TAB = ROOT / "paper" / "tables"
TEX = ROOT / "paper" / "GB_META_v2.tex"


def load():
    return {p.stem: pd.read_csv(p) for p in TAB.glob("*.csv")}


def build_checks(d):
    """(label, value_in_paper, value_from_source, tolerance) triples."""
    edge = d["table2_results_edge_iiotset"].set_index("model")
    head = d["table0_headline"].set_index("dataset")
    leak = d["table1_leakage_audit"].set_index("dataset")
    mem = d["table1b_memorisation_ceiling"].set_index("dataset")
    hpo = d["table11_hpo"].iloc[0]
    var = d["table5_seed_variance"]
    nbt = d["table5b_corrected_paired_t"].set_index("dataset")
    merge = d["table12_class_merging"].set_index("dataset")
    e = head.loc["edge_iiotset"]
    c = []

    def seed(dataset, model, col):
        r = var[(var.dataset == dataset) & (var.model == model)]
        return float(r.iloc[0][col])

    # -- abstract and results: seed-aware headline --------------------------
    c += [
        ("GB-META seed mean (Edge)", 0.9225, seed("edge_iiotset", "GB-META", "mean"), 5e-5),
        ("GB-META seed sd (Edge)", 0.0026, seed("edge_iiotset", "GB-META", "std"), 5e-5),
        ("CatBoost seed mean (Edge)", 0.9163, seed("edge_iiotset", "CatBoost", "mean"), 5e-5),
        ("CatBoost seed sd (Edge)", 0.0014, seed("edge_iiotset", "CatBoost", "std"), 5e-5),
        ("Edge corrected delta", 0.0062, nbt.loc["edge_iiotset", "mean_difference"], 5e-5),
        ("Edge corrected p", 0.124, nbt.loc["edge_iiotset", "p"], 5e-4),
        ("UNSW corrected delta", -0.0214, nbt.loc["unsw_nb15", "mean_difference"], 5e-5),
        ("UNSW corrected p", 0.005, nbt.loc["unsw_nb15", "p"], 5e-4),
        ("GB-META within-split delta", 0.0080, e["delta"], 5e-5),
        ("GB-META ECE (ref seed)", 0.0051, edge.loc["GB-META", "ece"], 5e-5),
        ("random forest ECE", 0.0467, edge.loc["Random Forest", "ece"], 5e-5),
        ("ResAttDNN ECE", 0.0726, edge.loc["ResAttDNN", "ece"], 5e-5),
        ("decision tree macro-F1", 0.9189, edge.loc["Decision Tree", "macro_f1"], 5e-5),
    ]

    # -- full-scale Edge-IIoTset replication --------------------------------
    fs = d["table14_fullscale"].set_index(d["table14_fullscale"].columns[0])
    c += [
        ("full-scale GB-META mean", 0.9238, fs.loc["GB-META", "full_mean"], 5e-5),
        ("full-scale GB-META sd", 0.0046, fs.loc["GB-META", "full_std"], 5e-5),
    ]

    # -- rare-class merging, quantified in the limitations ------------------
    c += [
        ("NSL-KDD classes merged", 10, merge.loc["NSL-KDD", "classes_merged"], 0),
        ("NSL-KDD merged rows", 92, merge.loc["NSL-KDD", "merged_rows"], 0),
        ("NSL-KDD merged fraction %", 0.073,
         100 * merge.loc["NSL-KDD", "merged_row_fraction"], 5e-4),
        ("Edge smallest class", 358, merge.loc["Edge-IIoTset", "smallest_kept_class"], 0),
        ("ToN-IoT smallest class", 646, merge.loc["ToN-IoT", "smallest_kept_class"], 0),
        ("UNSW smallest class", 127, merge.loc["UNSW-NB15", "smallest_kept_class"], 0),
    ]

    # -- leakage audit ------------------------------------------------------
    c += [
        ("UNSW duplicate rate %", 38.6, 100 * leak.loc["unsw_nb15", "exact_duplicate_rate"], 0.05),
        ("ToN-IoT duplicate rate %", 18.5, 100 * leak.loc["ton_iot", "exact_duplicate_rate"], 0.05),
        ("NSL-KDD duplicate rate %", 0.0, 100 * leak.loc["nslkdd", "exact_duplicate_rate"], 0.05),
        ("NSL-KDD best single feature %", 86.7,
         100 * leak.loc["nslkdd", "best_single_feature_acc"], 0.05),
        ("NSL-KDD majority baseline %", 53.0,
         100 * leak.loc["nslkdd", "majority_baseline"], 0.05),
        ("Edge memorisation ceiling", 0.342, mem.loc["Edge-IIoTset", "memorisation_ceiling"], 5e-4),
        ("ToN-IoT memorisation ceiling", 0.825, mem.loc["ToN-IoT", "memorisation_ceiling"], 5e-4),
    ]

    # -- HPO ----------------------------------------------------------------
    c += [
        ("Optuna val gain", 0.0032, hpo["val_gain"], 5e-5),
        ("Optuna test gain", 0.0024, hpo["test_gain"], 5e-5),
        ("Optuna trials", 15, hpo["trials"], 0),
        ("Optuna seconds", 212, hpo["seconds"], 0.5),
    ]

    return c


def full_body() -> str:
    """The manuscript with every \\input file inlined.

    Some quoted figures live only in a generated table, so the presence check has
    to see the same text pdflatex does.
    """
    text = TEX.read_text(encoding="utf-8")
    for m in re.finditer(r"\\input\{([^}]+)\}", text):
        p = TEX.parent / m.group(1)
        p = p if p.suffix else p.with_suffix(".tex")
        if p.exists():
            text += "\n" + p.read_text(encoding="utf-8")
    return text


def main() -> int:
    checks = build_checks(load())
    body = full_body()

    print("=== paper numbers vs source artefacts ===\n")
    print(f"  {'claim':<32}{'in paper':>12}{'in source':>13}   status")
    bad = 0
    for label, paper_val, src_val, tol in checks:
        src_val = float(src_val)
        ok = abs(paper_val - src_val) <= tol
        bad += not ok
        print(f"  {label:<32}{paper_val:>12.5g}{src_val:>13.5g}   "
              f"{'ok' if ok else 'MISMATCH'}")

    # Every figure above should also actually occur in the manuscript text.
    print("\n=== are the quoted figures present in the .tex? ===")
    missing = []
    for label, paper_val, _, _ in checks:
        s = f"{paper_val:g}"
        variants = {s, s.lstrip("0"), f"{paper_val:,.0f}" if paper_val >= 1000 else s}
        if paper_val >= 1000:
            variants.add(f"{int(paper_val):,}".replace(",", "{,}"))
        if not any(v in body for v in variants):
            missing.append((label, s))
    if missing:
        for label, s in missing:
            print(f"  note: {label} ({s}) not found verbatim; check it is phrased differently")
    else:
        print("  all present")

    print("\n" + "=" * 62)
    print("FAIL: {} number(s) disagree with their source".format(bad) if bad
          else "PASS: every checked number matches its source artefact")
    return 1 if bad else 0


if __name__ == "__main__":
    sys.exit(main())
